/*The product with the highest reviews , the day it was ordered the most, either that day was a 
public holiday,  total review points, percentage distribution of the review points , 
and percentage distribution of early shipments to late shipments for that particular product.

ingestion_date date NOT NULL
product_name varchar NOT NULL
most_ordered_day date NOT NULL
is_public_holiday bool NOT NULL
tt_review_points int NOT NULL
pct_one_star_review float NOT NULL
pct_two_star_review float NOT NULL
pct_three_star_review float NOT NULL
pct_four_star_review float NOT NULL
pct_five_star_review float NOT NULL
pct_early_shipments float NOT NULL
pct_late_shipments float NOT NULL
*/


-------------------REVIEWS BREAKDOWN----------------------------------------
WITH PRODUCT_REVIEW_POINT AS (
SELECT PRODUCT_ID, REVIEW, 
        COUNT(REVIEW) REVIEW_COUNT, SUM(REVIEW) REVIEW_TOTAL,
        SUM(SUM(REVIEW)) OVER(PARTITION BY PRODUCT_ID) TT_REVIEW_POINTS
FROM {{source('s3','REVIEWS')}}
GROUP BY 1,2
ORDER BY 1, 2
)
,BEST_PRODUCT_REVIEW AS (
    SELECT PRODUCT_ID, REVIEW, REVIEW_TOTAL, TT_REVIEW_POINTS
    FROM PRODUCT_REVIEW_POINT
    WHERE TT_REVIEW_POINTS = (SELECT MAX(TT_REVIEW_POINTS) FROM PRODUCT_REVIEW_POINT)
)
,TRANS_BEST_PRODUCT_REVIEW AS (
    SELECT PRODUCT_ID, 
    (SELECT REVIEW FROM BEST_PRODUCT_REVIEW WHERE REVIEW = 1) REVIEW_1, 
    (SELECT REVIEW_TOTAL FROM BEST_PRODUCT_REVIEW WHERE REVIEW = 1) REVIEW_1_TOTAL, 
    (SELECT REVIEW FROM BEST_PRODUCT_REVIEW WHERE REVIEW = 2) REVIEW_2, 
    (SELECT REVIEW_TOTAL FROM BEST_PRODUCT_REVIEW WHERE REVIEW = 2) REVIEW_2_TOTAL,
    (SELECT REVIEW FROM BEST_PRODUCT_REVIEW WHERE REVIEW = 3) REVIEW_3, 
    (SELECT REVIEW_TOTAL FROM BEST_PRODUCT_REVIEW WHERE REVIEW = 3) REVIEW_3_TOTAL,
    (SELECT REVIEW FROM BEST_PRODUCT_REVIEW WHERE REVIEW = 4) REVIEW_4, 
    (SELECT REVIEW_TOTAL FROM BEST_PRODUCT_REVIEW WHERE REVIEW = 4) REVIEW_4_TOTAL,
    (SELECT REVIEW FROM BEST_PRODUCT_REVIEW WHERE REVIEW = 5) REVIEW_5, 
    (SELECT REVIEW_TOTAL FROM BEST_PRODUCT_REVIEW WHERE REVIEW = 5) REVIEW_5_TOTAL,
    TT_REVIEW_POINTS
    FROM BEST_PRODUCT_REVIEW
    LIMIT 1
)
-------------------ORDERS BREAKDOWN----------------------------------------
, BEST_PRODUCT_ORDER_SHIPMENT AS(
 SELECT DISTINCT O.ORDER_ID, O.ORDER_DATE, O.PRODUCT_ID, 
        O.UNIT_PRICE, O.QUANTITY, O.AMOUNT
        ,SD.SHIPMENT_ID, SD.SHIPMENT_DATE, SD.DELIVERY_DATE,
        DATEDIFF(DAY, ORDER_DATE, SHIPMENT_DATE) DAYS_TO_SHIP,
        CASE WHEN (DATEDIFF(DAY, ORDER_DATE, SHIPMENT_DATE) >= 6 AND DELIVERY_DATE IS NULL) THEN 'Late'
            WHEN (SHIPMENT_DATE IS NULL AND DELIVERY_DATE IS NULL 
                    AND DATEDIFF(DAY, ORDER_DATE, '2022-09-05') >= 15) THEN 'Undelivered'
            ELSE 'Early'
        END SHIPMENT_TYPE
FROM {{source('s3', 'ORDERS')}} O
LEFT JOIN {{source('s3', 'SHIPMENT_DELIVERIES')}} SD
ON O.ORDER_ID = SD.ORDER_ID
LEFT JOIN PRODUCT_REVIEW_POINT PRP
ON PRP.PRODUCT_ID = O.PRODUCT_ID
WHERE TT_REVIEW_POINTS = (SELECT MAX(TT_REVIEW_POINTS) FROM PRODUCT_REVIEW_POINT)
)
,REF_ORDER_SHIPMENT AS (
    SELECT PRODUCT_ID, MAX(ORDER_DATE) MAX_DATE, QUANTITY, 
    (SELECT COUNT(ORDER_ID) FROM BEST_PRODUCT_ORDER_SHIPMENT) TOTAL_ORDERS, 
    (SELECT COUNT(ORDER_ID) FROM BEST_PRODUCT_ORDER_SHIPMENT WHERE SHIPMENT_TYPE = 'Early') EARLY_SHIPMENTS,
    (SELECT COUNT(ORDER_ID) FROM BEST_PRODUCT_ORDER_SHIPMENT WHERE SHIPMENT_TYPE = 'Late') LATE_SHIPMENTS,
    (SELECT COUNT(ORDER_ID) FROM BEST_PRODUCT_ORDER_SHIPMENT WHERE SHIPMENT_TYPE = 'Undelivered') UNDELIVERED_SHIPMENTS
    FROM BEST_PRODUCT_ORDER_SHIPMENT
    WHERE QUANTITY = (SELECT MAX(QUANTITY) FROM BEST_PRODUCT_ORDER_SHIPMENT)
    GROUP BY 1, 3, 4, 5, 6, 7
)

SELECT DATE(SYSDATE()) INGESTION_DATE, DP.PRODUCT_NAME,  ROS.MAX_DATE MOST_ORDERED_DAY,
        CASE WHEN DD.WORKING_DAY = 'True' THEN 'False' 
             WHEN DD.WORKING_DAY = 'False' THEN 'True'
        END IS_PUBLIC_HOLIDAY,
        TT_REVIEW_POINTS,
        ROUND(((REVIEW_1_TOTAL / TT_REVIEW_POINTS) * 100),2) PCT_ONE_STAR_REVIEW,
        ROUND(((REVIEW_2_TOTAL / TT_REVIEW_POINTS) * 100),2) PCT_TWO_STAR_REVIEW,
        ROUND(((REVIEW_3_TOTAL / TT_REVIEW_POINTS) * 100),2) PCT_THREE_STAR_REVIEW, 
        ROUND(((REVIEW_4_TOTAL / TT_REVIEW_POINTS) * 100),2) PCT_FOUR_STAR_REVIEW,
        ROUND(((REVIEW_5_TOTAL / TT_REVIEW_POINTS) * 100),2) PCT_FIVE_STAR_REVIEW,
        ROUND(((EARLY_SHIPMENTS / TOTAL_ORDERS) * 100),2) PCT_EARLY_SHIPMENTS,
        ROUND(((LATE_SHIPMENTS / TOTAL_ORDERS) * 100),2) PCT_LATE_SHIPMENTS 
FROM REF_ORDER_SHIPMENT ROS
JOIN TRANS_BEST_PRODUCT_REVIEW TBPR
ON ROS.PRODUCT_ID = TBPR.PRODUCT_ID
JOIN {{source('rds','DIM_PRODUCTS')}} DP
ON ROS.PRODUCT_ID = DP.PRODUCT_ID
JOIN {{source('rds','DIM_DATES')}} DD
ON ROS.MAX_DATE = DD.CALENDAR_DT