version: 2

sources:

  - name: s3
    database: MUR_DATA2BOT
    schema: S3DATA
    tables:
      - name: ORDERS
      - name: REVIEWS
      - name: SHIPMENT_DELIVERIES

  - name: rds
    database: MUR_DATA2BOT
    schema: S3DATA
    tables:
      - name: DIM_DATES
      - name: DIM_PRODUCTS
      - name: DIM_CUSTOMERS
      - name: DIM_ADDRESSES